// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: gamer-proxy.proto

#include "gamer-proxy.pb.h"
#include "gamer-proxy.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* PlayerProxy_method_names[] = {
  "/PlayerProxy/Move",
};

std::unique_ptr< PlayerProxy::Stub> PlayerProxy::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PlayerProxy::Stub> stub(new PlayerProxy::Stub(channel));
  return stub;
}

PlayerProxy::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Move_(PlayerProxy_method_names[0], ::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::JsonMessage, ::JsonMessage>* PlayerProxy::Stub::MoveRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::JsonMessage, ::JsonMessage>::Create(channel_.get(), rpcmethod_Move_, context);
}

::grpc::ClientAsyncReaderWriter< ::JsonMessage, ::JsonMessage>* PlayerProxy::Stub::AsyncMoveRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::JsonMessage, ::JsonMessage>::Create(channel_.get(), cq, rpcmethod_Move_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::JsonMessage, ::JsonMessage>* PlayerProxy::Stub::PrepareAsyncMoveRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::JsonMessage, ::JsonMessage>::Create(channel_.get(), cq, rpcmethod_Move_, context, false, nullptr);
}

PlayerProxy::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PlayerProxy_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< PlayerProxy::Service, ::JsonMessage, ::JsonMessage>(
          std::mem_fn(&PlayerProxy::Service::Move), this)));
}

PlayerProxy::Service::~Service() {
}

::grpc::Status PlayerProxy::Service::Move(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::JsonMessage, ::JsonMessage>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


