// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gamer-proxy.proto

#ifndef PROTOBUF_INCLUDED_gamer_2dproxy_2eproto
#define PROTOBUF_INCLUDED_gamer_2dproxy_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_gamer_2dproxy_2eproto 

namespace protobuf_gamer_2dproxy_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_gamer_2dproxy_2eproto
class JsonMessage;
class JsonMessageDefaultTypeInternal;
extern JsonMessageDefaultTypeInternal _JsonMessage_default_instance_;
namespace google {
namespace protobuf {
template<> ::JsonMessage* Arena::CreateMaybeMessage<::JsonMessage>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class JsonMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:JsonMessage) */ {
 public:
  JsonMessage();
  virtual ~JsonMessage();

  JsonMessage(const JsonMessage& from);

  inline JsonMessage& operator=(const JsonMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  JsonMessage(JsonMessage&& from) noexcept
    : JsonMessage() {
    *this = ::std::move(from);
  }

  inline JsonMessage& operator=(JsonMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const JsonMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const JsonMessage* internal_default_instance() {
    return reinterpret_cast<const JsonMessage*>(
               &_JsonMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(JsonMessage* other);
  friend void swap(JsonMessage& a, JsonMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline JsonMessage* New() const final {
    return CreateMaybeMessage<JsonMessage>(NULL);
  }

  JsonMessage* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<JsonMessage>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const JsonMessage& from);
  void MergeFrom(const JsonMessage& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JsonMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string json = 1;
  void clear_json();
  static const int kJsonFieldNumber = 1;
  const ::std::string& json() const;
  void set_json(const ::std::string& value);
  #if LANG_CXX11
  void set_json(::std::string&& value);
  #endif
  void set_json(const char* value);
  void set_json(const char* value, size_t size);
  ::std::string* mutable_json();
  ::std::string* release_json();
  void set_allocated_json(::std::string* json);

  // @@protoc_insertion_point(class_scope:JsonMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr json_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_gamer_2dproxy_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// JsonMessage

// string json = 1;
inline void JsonMessage::clear_json() {
  json_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& JsonMessage::json() const {
  // @@protoc_insertion_point(field_get:JsonMessage.json)
  return json_.GetNoArena();
}
inline void JsonMessage::set_json(const ::std::string& value) {
  
  json_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:JsonMessage.json)
}
#if LANG_CXX11
inline void JsonMessage::set_json(::std::string&& value) {
  
  json_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:JsonMessage.json)
}
#endif
inline void JsonMessage::set_json(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  json_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:JsonMessage.json)
}
inline void JsonMessage::set_json(const char* value, size_t size) {
  
  json_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:JsonMessage.json)
}
inline ::std::string* JsonMessage::mutable_json() {
  
  // @@protoc_insertion_point(field_mutable:JsonMessage.json)
  return json_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* JsonMessage::release_json() {
  // @@protoc_insertion_point(field_release:JsonMessage.json)
  
  return json_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JsonMessage::set_allocated_json(::std::string* json) {
  if (json != NULL) {
    
  } else {
    
  }
  json_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), json);
  // @@protoc_insertion_point(field_set_allocated:JsonMessage.json)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_gamer_2dproxy_2eproto
