// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: player.proto

#include "player.pb.h"
#include "player.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* PlayerProxy_method_names[] = {
  "/PlayerProxy/Move",
};

std::unique_ptr< PlayerProxy::Stub> PlayerProxy::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PlayerProxy::Stub> stub(new PlayerProxy::Stub(channel, options));
  return stub;
}

PlayerProxy::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Move_(PlayerProxy_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::JsonMessage, ::JsonMessage>* PlayerProxy::Stub::MoveRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::JsonMessage, ::JsonMessage>::Create(channel_.get(), rpcmethod_Move_, context);
}

void PlayerProxy::Stub::async::Move(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::JsonMessage,::JsonMessage>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::JsonMessage,::JsonMessage>::Create(stub_->channel_.get(), stub_->rpcmethod_Move_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::JsonMessage, ::JsonMessage>* PlayerProxy::Stub::AsyncMoveRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::JsonMessage, ::JsonMessage>::Create(channel_.get(), cq, rpcmethod_Move_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::JsonMessage, ::JsonMessage>* PlayerProxy::Stub::PrepareAsyncMoveRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::JsonMessage, ::JsonMessage>::Create(channel_.get(), cq, rpcmethod_Move_, context, false, nullptr);
}

PlayerProxy::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PlayerProxy_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< PlayerProxy::Service, ::JsonMessage, ::JsonMessage>(
          [](PlayerProxy::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::JsonMessage,
             ::JsonMessage>* stream) {
               return service->Move(ctx, stream);
             }, this)));
}

PlayerProxy::Service::~Service() {
}

::grpc::Status PlayerProxy::Service::Move(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::JsonMessage, ::JsonMessage>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


