[[jobs]]
name = "mkdir"
run = "/usr/bin/mkdir -p ${cwd}/cmake/build"

[[jobs]]
name = "cp_cmake_common_file"
run = "/usr/bin/cp ${cmake_lists_common} ${cwd}"

[[jobs]]
name = "cp_cmake_file"
run = "/usr/bin/cp ${cmake_lists} ${cwd}"

[[jobs]]
name = "chown"
run = "/usr/bin/chown -R 1919:1919 ${cwd}/cmake"

[[jobs]]
name = "cmake"
run = "/usr/bin/cmake -DPLAYER_PROTO_FILE_PATH=${PLAYER_PROTO_FILE_PATH} -DBOT_H=${BOT_H} -DPLAYER_PROXY_CLIENT_H=${PLAYER_PROXY_CLIENT_H} -DINPUT_BOT_FILE_NAME=${INPUT_BOT_FILE_NAME} -D_FINDPACKAGE_PROTOBUF_CONFIG_HINTS=${_FINDPACKAGE_PROTOBUF_CONFIG_HINTS} ../.."
[jobs.jail]
mount = ["${cwd}"]
mount_readonly = [
  "/bin",
  "/lib",
  "/lib64/",
  "/usr/",
  "/sbin/",
  "/dev",
  "/dev/urandom",
  "${@src}/game/players/playerProxy/grpc",
  "${@src}/game/gamerules/local/GuessNumber/bot_template/cpp",
  "${@src}/game/gamerules/local/GuessNumber/bots/cpp/bot2",
  "/home/shiyuzhe/.local",
]
timeout = 10
mem_max = 256
user = 1919
group = 1919
pid_max = 32
cwd = "${cwd}/cmake/build"
safetySetup = true
[jobs.jail.env]
PATH = "${PATH}"
CMAKE_PREFIX_PATH = "/home/shiyuzhe/.local"
really_quiet = "true"

[[jobs]]
name = "cached make"
run = "/usr/bin/make -j2"
verbose = true
[jobs.jail]
mount = ["${cwd}", "/tmp/ccache_cache"]
mount_readonly = [
  "/bin",
  "/lib",
  "/usr/",
  "/lib64/",
  "/sbin/",
  "/dev",
  "/dev/urandom",
  "${@src}/game/players/playerProxy/grpc",
  "${@src}/game/gamerules/local/GuessNumber/bot_template/cpp",
  "${@src}/game/gamerules/local/GuessNumber/bots/cpp/bot2",
  "/home/shiyuzhe/.local",
  "${@src}/include/single_include/nlohmann",
]
timeout = 120
mem_max = 512
file_sz_limit = 1024000
file_no_limit = 1024
user = 1919
group = 1919
cwd = "${cwd}/cmake/build"
[jobs.jail.env]
PATH = "${PATH}"
CPLUS_INCLUDE_PATH = "${CPLUS_INCLUDE_PATH}"
CCACHE_DIR = "/tmp/ccache_cache"

[constants]
PLAYER_PROTO_FILE_PATH = "${@src}/game/players/playerProxy/grpc/player.proto"
BOT_H = "${@src}/game/gamerules/local/GuessNumber/bot_template/cpp/bot.h"
PLAYER_PROXY_CLIENT_H = "${@src}/game/gamerules/local/GuessNumber/bot_template/cpp/player_proxy_client.h"
INPUT_BOT_FILE_NAME = "test"
HOME_LOCAL = "/home/shiyuzhe/.local"
_FINDPACKAGE_PROTOBUF_CONFIG_HINTS = "/home/shiyuzhe/.local/lib/cmake/protobuf"
CPLUS_INCLUDE_PATH = "/usr/include/x86_64-linux-gnu/c++/11:/usr/include/x86_64-linux-gnu/c++/11/bits:/usr/include/c++/11:/usr/include/c++/11/bits:/usr/include/c++/11/ext:/usr/include/x86_64-linux-gnu:/usr/include:${@src}/game/gamerules/local/GuessNumber/bot_template/cpp:${@src}/include/single_include/nlohmann"
cmake_lists = "${@src}/configs/cmakes/cpp_bot_use_template/CMakeLists.txt"
cmake_lists_common = "${@src}/configs/cmakes/cpp_bot_use_template/common.cmake"
PATH = "/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin"
